
ALTER TABLE ADDFRIEND ADD CONSTRAINT SAMEUSERCANNOTADDNEW CHECK (AddUserID <> ReceiverUserID)




ALTER TABLE ADDFRIEND
    WITH CHECK ADD CONSTRAINT ISADDFRIEND
    CHECK ('False'=dbo.IsThereFriendRequest(AddUserId,ReceiverUserID))




	ALTER TABLE PAGEADMIN
    WITH CHECK ADD CONSTRAINT ISANYMOD
    CHECK (0=dbo.IsThereAnyAdmin(PageID,UserID))

INSERT INTO PAGEADMIN VALUES (2,4)
select * from PAGEMOD