CREATE TABLE COUSER(
UserID int IDENTITY(1,1) PRIMARY KEY ,
username nvarchar(255) UNIQUE,
FName nvarchar(50) NOT NULL,
MName nvarchar(50),
LName nvarchar(50) not null,
Password nvarchar(20) not null,
MailCheckCode bit,
Active bit,
RecordDate datetime,
UserOnline bit
)

CREATE TABLE PROFILE(
ProfileID int IDENTITY(1,1) PRIMARY KEY,
Photo nvarchar(255),
CV text,
Bio text,
Job nvarchar(255),
)

CREATE TABLE EMAIL (
EmailID int  IDENTITY(1,1)  PRIMARY KEY ,
EmailAdress varchar(30) NOT NULL,
RecordDate varchar(30) NOT NULL,
active bit NOT NULL
)

CREATE TABLE COUNTRY (
CountryCode  int IDENTITY(1,1) PRIMARY KEY,
CountryName varchar(30) NOT NULL
)

CREATE TABLE CITY (
CityCode int IDENTITY(1,1) PRIMARY KEY,
CityName varchar(30) NOT NULL,
CountryCode int FOREIGN KEY REFERENCES Country(countryCode) NOT NULL
);

CREATE TABLE LOCALITY(
LocalityID int IDENTITY(1,1) PRIMARY KEY ,
LocalityName varchar(30) NOT NULL,
CityCode int FOREIGN KEY REFERENCES City(CityCode) NOT NULL
)

CREATE TABLE ADRESS(
AdressID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
StreetName varchar(30),
DoorNo int ,
LocalityCode int NOT NULL,
CountryCode int NOT NULL,
CityCode int
FOREIGN KEY (LocalityCode) REFERENCES LOCALITY(LocalityID),
FOREIGN KEY (CityCode) REFERENCES CITY(CityCode),
FOREIGN KEY (CountryCode) REFERENCES  COUNTRY(CountryCode)
)

CREATE TABLE STATU(
StatuID int PRIMARY KEY NOT NULL,
StatuText varchar(255) NOT NULL,
UserID int FOREIGN KEY REFERENCES COUSER(UserID)
)

CREATE TABLE LIKETYPE(
typeID int IDENTITY(1,1) PRIMARY KEY,
LikeType tinyint NOT NULL
)
CREATE TABLE STATULIKE(
likeID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
StatuID int  FOREIGN KEY REFERENCES STATU(statuID),
TypeID int FOREIGN KEY REFERENCES LIKETYPE(typeID),
UserID int FOREIGN KEY REFERENCES COUSER(userID)
)



CREATE TABLE COMMENT (
CommentID  int IDENTITY(1,1) PRIMARY KEY,
CommentText varchar(255) NOT NULL,
Photo nvarchar(60) NOT NULL,
StatuID int FOREIGN KEY REFERENCES STATU(statuID)
)
CREATE TABLE CATEGORY(
CategoryID int PRIMARY KEY IDENTITY(1,1) NOT NULL,
CategoryName varchar(30) NOT NULL
)

CREATE TABLE GRUP (
GrupID int IDENTITY(1,1) PRIMARY KEY,
Hakkinda varchar(255) ,
GName varchar(30) NOT NULL,
Photo nvarchar(30) ,
Cover nvarchar(30) ,
Active bit NOT NULL,
CategoryID int FOREIGN KEY REFERENCES CATEGORY(CategoryID),
CreateUserID int FOREIGN KEY REFERENCES COUSER(userID)
)

CREATE TABLE MESSAGEBOX(
BoxID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
UserID int FOREIGN KEY REFERENCES COUSER(userID)
)

CREATE TABLE MESSAGEITEM(
MessageID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
MessageText Nvarchar(255) NOT NULL,
Photo nvarchar(30),
BoxID int FOREIGN KEY REFERENCES MessageBox(boxID)
)

CREATE TABLE JOB(
JobID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
JobName Nvarchar(30) NOT NULL,
JobDescription Nvarchar(255) NOT NULL
)
CREATE TABLE SAYFA(
SayfaID int PRIMARY KEY IDENTITY(1,1) NOT NULL,
Hakkinda varchar(255) NOT NULL,
Photo nvarchar(60) ,
SayfaName varchar(30) NOT NULL,
Cover nvarchar(60) ,
Active bit,
CategoryID int NOT NULL FOREIGN KEY REFERENCES CATEGORY(CategoryID),
CreateUserID int NOT NULL FOREIGN KEY REFERENCES COUSER(UserID)
)

CREATE TABLE USERJOB(
UserJobID int PRIMARY KEY IDENTITY(1,1) NOT NULL,
SDate varchar(15) NOT NULL,
EDate varchar(15) ,
UserID int NOT NULL FOREIGN KEY REFERENCES COUSER (userID),
SayfaID int NOT NULL FOREIGN KEY REFERENCES SAYFA(sayfaID),
JobID int NOT NULL FOREIGN KEY REFERENCES Job(jobID)
)
CREATE TABLE HR(
HRID INT PRIMARY KEY IDENTITY(1,1),
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
)

CREATE TABLE ISILAN(
IlanID int PRIMARY KEY IDENTITY(1,1) NOT NULL,
IlanHours int NOT NULL,
WorkYear int NOT NULL,
IlanDescription varchar(255) NOT NULL,
CategoryID int NOT NULL FOREIGN KEY REFERENCES CATEGORY(CategoryID),
HRID   INT FOREIGN KEY REFERENCES HR(HRID),
);




CREATE TABLE ALBUM(
AlbumID int PRIMARY KEY IDENTITY(1,1) NOT NULL,
AlbumName varchar(30) NOT NULL
);

CREATE TABLE PHOTO(
PhotoID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
Photo nvarchar(60),
AlbumID int  FOREIGN KEY REFERENCES Album(AlbumID)
);

CREATE TABLE VIDEO(
VideoID int PRIMARY KEY IDENTITY(1,1) ,
Video nvarchar(60) NOT NULL,
AlbumID int NOT NULL FOREIGN KEY REFERENCES ALBUM(AlbumID)
);

CREATE TABLE USERFRIEND(
SenderID int FOREIGN KEY REFERENCES COUSER(UserID),
ReceiverID int FOREIGN KEY REFERENCES COUSER(UserID),
FriendDate datetime NOT NULL,
FriendshipCheck bit,
PRIMARY KEY(SenderID,ReceiverID)
)

CREATE TABLE REPLY(
ReplyID int PRIMARY KEY,
ReplyText varchar(255) ,
Photo nvarchar(60),
RecordDate datetime,
CommentID int FOREIGN KEY REFERENCES COMMENT(CommentID)
)

CREATE TABLE GRUPADMIN(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
GrupID INT FOREIGN KEY  REFERENCES GRUP(GrupID),
PRIMARY KEY(UserID,GrupID)
)

CREATE TABLE GRUPMOD(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
GrupID INT FOREIGN KEY  REFERENCES GRUP(GrupID),
PRIMARY KEY(UserID,GrupID)
)

CREATE TABLE SAYFAADMIN(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
SayfaID INT FOREIGN KEY  REFERENCES SAYFA(SayfaID),
PRIMARY KEY(UserID,SayfaID)
);

CREATE TABLE SAYFAMOD(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
SayfaID INT FOREIGN KEY  REFERENCES SAYFA(SayfaID),
PRIMARY KEY(UserID,SayfaID)
);

CREATE TABLE SAYFABEGENI(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY(UserID,SayfaID)
)

CREATE TABLE GRUPUYE(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
GrupID INT FOREIGN KEY  REFERENCES GRUP(GrupID),
PRIMARY KEY(UserID,GrupID)
)

CREATE TABLE ILANBASVURU(
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
IlanID INT FOREIGN KEY  REFERENCES ISILAN(IlanID),
PRIMARY KEY(UserID,IlanID)
)

CREATE TABLE SAYFAADRESS(
AdressID int FOREIGN KEY REFERENCES ADRESS(AdressID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY (AdressID)
)

CREATE TABLE GRUPADRESS(
AdressID int FOREIGN KEY REFERENCES ADRESS(AdressID),
GrupID int FOREIGN KEY REFERENCES GRUP(GrupID),
PRIMARY KEY (AdressID)
)

CREATE TABLE PROFILEADRESS(
AdressID int FOREIGN KEY REFERENCES ADRESS(AdressID),
ProfileID int FOREIGN KEY REFERENCES PROFILE(ProfileID),
PRIMARY KEY (AdressID)
)

CREATE TABLE UNIVERSITY(
SayfaID INT FOREIGN KEY REFERENCES SAYFA(SayfaID),
OgretimGorevliSayisi int, 
PRIMARY KEY (SayfaID)
)

CREATE TABLE COMPANY(
SayfaID int foreign key REFERENCES  SAYFA(SayfaID),
PRIMARY KEY(SayfaID)
)

CREATE TABLE COMMUNITY(
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY (SayfaID)
);

CREATE TABLE PROFILEALBUM (
AlbumID int FOREIGN KEY REFERENCES ALBUM(AlbumID),
ProfileID int FOREIGN KEY REFERENCES ALBUM(AlbumID),
PRIMARY KEY (AlbumID)
)

CREATE TABLE SAYFAALBUM (
AlbumID int FOREIGN KEY REFERENCES ALBUM(AlbumID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY (AlbumID)
)

CREATE TABLE GRUPALBUM (
AlbumID int FOREIGN KEY REFERENCES ALBUM(AlbumID),
GrupID int FOREIGN KEY REFERENCES GRUP(GrupID),
PRIMARY KEY (AlbumID)
)

CREATE TABLE SAYFABOX (

BoxID INT FOREIGN KEY REFERENCES MESSAGEBOX(BoxID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY (BoxID),
)

CREATE TABLE USERBOX (
BoxID INT FOREIGN KEY REFERENCES MESSAGEBOX(BoxID),
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
PRIMARY KEY (BoxID),
)

CREATE TABLE USERCOMMENT (
CommnetID int FOREIGN KEY REFERENCES COMMENT(CommentID),
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
PRIMARY KEY(CommnetID)
)

CREATE TABLE SAYFACOMMENT (
CommnetID int FOREIGN KEY REFERENCES COMMENT(CommentID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY(CommnetID)
)

CREATE TABLE USERSTATU(
StatuID int FOREIGN KEY REFERENCES STATU(StatuID),
UserID int FOREIGN KEY REFERENCES COUSER(UserID),
PRIMARY KEY(StatuID)
)

CREATE TABLE GRUPSTATU(
StatuID int FOREIGN KEY REFERENCES STATU(StatuID),
GrupID int FOREIGN KEY REFERENCES GRUP(GrupID),
PRIMARY KEY(StatuID)
)

CREATE TABLE SAYFASTATU(
StatuID int FOREIGN KEY REFERENCES STATU(StatuID),
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
PRIMARY KEY(StatuID)
)




CREATE TABLE MEZUN(
SayfaID int FOREIGN KEY REFERENCES SAYFA(SayfaID),
ProfileID int FOREIGN KEY REFERENCES PROFILE(ProfileID),
GDate datetime,
MDate datetime,
PRIMARY KEY (SayfaID,ProfileID)
)

